name: UI tests

on:
  workflow_dispatch:
    inputs:
      deployment_targets:
        description: Choose target
        required: true
        default: all tests
        type: choise
        options:
            - all tests

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    name: UI tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          check-latest: true

      - name: Install Google Chrome
        run: sudo apt-get install google-chrome-stable

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest --alluredir=allure-results

      - name: Store allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention-days: 1

  generate-report:
    runs-on: ubuntu-latest
    needs: ui-tests
    name: Generate report

    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: "microsoft"
          java-version: "17"
      - run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.25.0/allure-2.25.0.tgz && sudo tar -zxvf allure-2.25.0.tgz -C /opt/ && sudo ln -s /opt/allure-2.25.0/bin/allure /usr/bin/allure

      - name: Download all workflows run artifacts
        uses: actions/download-artifact@v4
      - run: allure generate -c allure-results -o _site

      - name: Store generated report
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path: _site
          retention-days: 1

  publish-report:
    runs-on: ubuntu-latest
    needs: generate-report
    name: Report publications
    steps:
      - name: Download all workflows run artifacts
        uses: actions/download-artifact@v4
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3